import {StyleSheet} from 'react-native';

const searchScreenStyles = (textSize, theme) =>
  StyleSheet.create({
    mainView: {
      flex: 1,
    },
    linearGradientBackground: {
      padding: 40,
      flex: 1,
      alignContent: 'center',
      justifyContent: 'center',
      alignItems: 'center',
    },
    lottie: {
      height: textSize.lottieheight,
      position: 'relative',
      top: -15,
    },
    text: {
      fontSize: textSize.searchheader,
      fontFamily: 'SpaceMonoRegular',
      color: theme.text1,
      letterSpacing: 3,
      textAlign: 'center',
      marginBottom: 15,
    },
    textInputView: {
      flexDirection: 'row',
      marginTop: 20,
      marginBottom: 25,
    },
    textInput: {
      paddingLeft: 10,
      backgroundColor: theme.text1,
      width: textSize.textinputwidth,
      borderTopLeftRadius: 15,
      borderBottomLeftRadius: 15,
      color: theme.textbg1,
      fontFamily: 'SpaceMonoRegular',
      fontSize: textSize.textinputsize,
      letterSpacing: 2,
    },
    textInputLinearGradient: {
      backgroundColor: theme.text1,
      width: textSize.textinputwidth,
      justifyContent: 'center',
      alignItems: 'center',
    },
    textInputLabel: {
      fontFamily: 'SpaceMonoRegular',
      fontSize: textSize.textinputsize,
      letterSpacing: 2,
      position: 'relative',
      top: -2,
    },
    buttonLinearGradient: {
      padding: 3,
      borderRadius: 15,
      marginTop: 20,
      marginBottom: 20,
      alignContent: 'center',
      justifyContent: 'center',
      alignItems: 'center',
    },
    buttonText: {
      textAlign: 'center',
      fontFamily: 'SpaceMonoRegular',
      color: theme.text1,
      fontSize: textSize.btns,
      position: 'relative',
      letterSpacing: 2,
      top: -2,
    },
    modal: {
      marginBottom: 150,
      marginTop: 150,
      marginLeft: 40,
      marginRight: 40,
    },
    modalView: {
      flexDirection: 'column',
      alignContent: 'center',
      // justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 25,
      backgroundColor: theme.appbg1,
      padding: 25,
    },
    modalImage: {
      height: textSize.modalpicheight,
      width: textSize.modalpicheight,
      borderRadius: 40,
      marginTop: 15,
      borderColor: theme.text1,
      borderWidth: 1,
    },
    modalTextMain: {
      fontSize: textSize.searchheader + 5,
      fontFamily: 'SpaceMonoRegular',
      color: theme.text1,
      letterSpacing: 2,
      textAlign: 'center',
      padding: 15,
      lineHeight: 35,
    },
    modalTextSecondary: {
      fontSize: textSize.textinputsize,
      fontFamily: 'SpaceMonoRegular',
      color: theme.text1,
      letterSpacing: 2,
      textAlign: 'center',
      marginBottom: 25,
      padding: 15,
      lineHeight: 35,
    },
    modalButtonLinearGradient: {
      padding: 3,
      borderRadius: 15,
      marginBottom: 15,
    },
    modalButtonText: {
      textAlign: 'center',
      fontFamily: 'SpaceMonoRegular',
      color: theme.text1,
      fontSize: textSize.btns,
      position: 'relative',
      top: -2,
    },
  });

export default searchScreenStyles;
